### ISSUE TITLE
Display linked images

### ISSUE THREAD

**Issue by jomo** [Jake0oo0/chatter#14]
For example as Colloquy does it with the [Succinct theme](https://github.com/JohnAlbin/succinct-for-colloquy) (which might be a good inspiration overall, apart from the colors):
![screenshot](https://i.imgur.com/o3tlx8M.png)

**Comment by jengel3** [comment]
Planning on it once I write the code for embedded items. That will probably be part of the plugin API, so you can add your own commands, receive events, and add custom embeds. Thanks :)
